### ISSUE TITLE
.NET 4.0 binary

### ISSUE THREAD

**Issue by jgillich** [tejacques/Option#10]
I am currently stuck on .NET 4.0. Can you provide a binary for it on NuGet?

**Comment by tejacques** [comment]
Wow this was a super dumb error on my part -- I swapped the version to 4.5 to test speed differences and never swapped it back to 3.5.

This should be up soon.

**Comment by tejacques** [comment]
Update your nuget package and this should work now.

**Comment by jgillich** [comment]
Awesome, thanks!
